# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- prod

pool:
  name: raspberry

steps:
- script: node /root/shell/push/release.js chatPVT
  displayName: 'Releasing chatPVT'
