apiVersion: apps/v1
kind: Deployment
metadata:
  name: evolua
  labels:
    app: evolua
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evolua
      version: v1
  template:
    metadata:
      labels:
        app: evolua
        version: v1
    spec:
      containers:
      - name: evolua
        image: docker.io/quirinobytes/evolua@sha256:53ec2d843427fd44f486f329763b5accc964a0fce528399bc1a584a05047082d
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_SERVER
          value: "mongodb-dev.default.svc.cluster.local"
        - name: MONGO_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongoserver
              key: username
        - name: MONGO_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongoserver
              key: password
        - name: MONGO_SERVER_ROLE
          value: "admin"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        volumeMounts:
        - mountPath: /usr/src/app/audioupload
          name: evolua-audioupload-pv
        - mountPath: /usr/src/app/fileuploadMural
          name: evolua-fileuploadmural-pv
        - mountPath: /usr/src/app/videoupload
          name: evolua-videoupload-pv
        - mountPath: /usr/src/app/fileupload
          name: evolua-fileupload-pv
      volumes:
      - name: evolua-audioupload-pv
        persistentVolumeClaim:
          claimName: evolua-audioupload-pvc
      - name: evolua-fileupload-pv
        persistentVolumeClaim:
          claimName: evolua-fileupload-pvc
      - name: evolua-fileuploadmural-pv
        persistentVolumeClaim:
          claimName: evolua-fileuploadmural-pvc
      - name: evolua-videoupload-pv
        persistentVolumeClaim:
          claimName: evolua-videoupload-pvc


