apiVersion: v1
kind: PersistentVolume
metadata:
  name: evolua-videoupload-pv
spec:
  #storageClassName: manual
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /k8s/evolua/videoupload
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1-kube
 
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evolua-videoupload-pvc
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
