apiVersion: v1
kind: PersistentVolume
metadata:
  name: evolua-videoupload-pv
spec:
  #storageClassName: manual
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /k8s/evolua/videoupload
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evolua-videoupload-pvc
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
